; IPKVM ESP32-S3 USB HID Keyboard Emulator
; COM port → receives commands from Mac
; USB port → sends keystrokes to DeskPC

[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 115200
upload_port = /dev/cu.usbmodem589B0309831
monitor_port = /dev/cu.usbmodem589B0309831
build_unflags = -DARDUINO_USB_MODE=1
build_flags =
    -DARDUINO_USB_MODE=0
    -DARDUINO_USB_CDC_ON_BOOT=0
